# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: todo-nodejs-mongo-aks
metadata:
  template: todo-nodejs-mongo-aks@0.0.1-beta
workflows:
  up: 
    steps:
      - azd: provision
      - azd: deploy --all
pipeline:
  variables:
    - AZURE_PRINCIPAL_TYPE
services:
  todo:
    host: aks
    containers:
      web:
        project: ./src/web
        dist: dist
        language: js
      api:
        project: ./src/api
        language: js
hooks:
  postdeploy:
    windows:
      shell: pwsh
      run: azd env set REACT_APP_API_BASE_URL $env:SERVICE_TODO_ENDPOINT_URL
    posix:
      shell: sh
      run: azd env set REACT_APP_API_BASE_URL ${SERVICE_TODO_ENDPOINT_URL}