# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: todo-nodejs-mongo-aks
metadata:
  template: todo-nodejs-mongo-aks@0.0.1-beta
workflows:
  up:
    steps:
      - azd: provision
      - azd: deploy --all
pipeline:
  variables:
    - AZURE_PRINCIPAL_TYPE
hooks:
  prebuild:
    shell: sh
    continueOnError: false
    interactive: true
    run: echo "PREBUILD HOOK"
  postbuild:
    shell: sh
    continueOnError: false
    interactive: true
    run: echo "POSTBUILD HOOK"
services:
  web:
    project: ./src/web
    dist: dist
    language: js
    host: aks
    hooks:
      # using predeploy hook for web until
      # https://github.com/Azure/azure-dev/issues/3546 is fixed
      prebuild:
        windows:
          shell: pwsh
          run: 'echo "VITE_API_BASE_URL=""$env:API_BASE_URL""" > .env.local ; echo "VITE_APPLICATIONINSIGHTS_CONNECTION_STRING=""$env:APPLICATIONINSIGHTS_CONNECTION_STRING""" >> .env.local'
        posix:
          shell: sh
          run: 'echo VITE_API_BASE_URL=\"$API_BASE_URL\" > .env.local && echo VITE_APPLICATIONINSIGHTS_CONNECTION_STRING=\"$APPLICATIONINSIGHTS_CONNECTION_STRING\" >> .env.local'
      postbuild:
        windows:
          shell: pwsh
          run: "rm .env.local"
        posix:
          shell: sh
          run: "rm .env.local"
  api:
    project: ./src/api
    language: js
    host: aks
    k8s:
      ingress:
        relativePath: api
    hooks:
      postdeploy:
        windows:
          shell: pwsh
          run: azd env set API_BASE_URL $env:SERVICE_API_ENDPOINT_URL
        posix:
          shell: sh
          run: azd env set API_BASE_URL ${SERVICE_API_ENDPOINT_URL}
