apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-api-config
data:
  AZURE_AKS_IDENTITY_CLIENT_ID: {{.Values.cluster.ClientId}}
  AZURE_KEY_VAULT_ENDPOINT: {{.Values.keyvault.endpoint}}
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{.Values.appInsights.connectionString}}